(()=>{let tok='',me=null,D={cars:[],records:[],users:[]},season='',carSearch='';const $=x=>document.getElementById(x),e=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function api(action,p={}){const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json',...(tok?{Authorization:'Bearer '+tok}:{})},body:JSON.stringify({action,...p})});const j=await r.json().catch(()=>({error:'SERVER'}));if(!r.ok){let x=new Error(j.error);x.code=j.error;throw x}return j}
function note(el,t,c='msg'){el.innerHTML='<div class="'+c+'">'+e(t)+'</div>'}
async function login(){let p=$('pin').value.replace(/\D/g,'').slice(0,2);$('pin').value=p;if(p.length!==2)return note($('loginMsg'),'Kód má 2 číslice.','msg err');try{let r=await api('login',{pin:p});tok=r.token;me=r.user;$('login').hidden=true;$('main').hidden=false;$('who').textContent=me.name+(me.role==='admin'?' · Admin':'');$('adminTab').style.display=me.role==='admin'?'':'none';$('pin').value='';await refresh();if(!matchMedia('(display-mode: standalone)').matches&&/iPhone|iPad|iPod/.test(navigator.userAgent))$('install').hidden=false}catch(x){note($('loginMsg'),x.code==='LOCKED'?'Příliš mnoho pokusů. Zkus to později.':'Špatný kód.','msg err')}}
$('loginBtn').onclick=login;$('pin').onkeydown=x=>{if(x.key==='Enter')login()};$('lock').onclick=()=>{tok='';me=null;$('main').hidden=true;$('login').hidden=false;$('loginMsg').innerHTML='';$('pin').focus()};
async function refresh(){try{D=await api('state');render()}catch(x){if(x.code==='AUTH')$('lock').click()}}
function latest(id,s){return D.records.find(r=>r.carId===id&&(!s||r.season===s))}
function valid(){let d=$('dot').value.replace(/\D/g,'').slice(0,4),k=$('km').value.replace(/\D/g,'').slice(0,7);$('dot').value=d;$('km').value=k;$('save').disabled=!($('car').value&&season&&/^\d{4}$/.test(d)&&+d.slice(0,2)>=1&&+d.slice(0,2)<=53&&k!=='');let l=latest($('car').value);$('kmHint').textContent=l?'Poslední evidovaný stav: '+Number(l.mileage).toLocaleString('cs-CZ')+' km.':'Aktuální stav tachometru v km.'}
$('dot').oninput=valid;$('km').oninput=valid;
function recentKey(){return 'dotRecentCars:'+(me?.id||'guest')}
function getRecent(){try{return JSON.parse(localStorage.getItem(recentKey())||'[]').filter(id=>D.cars.some(c=>c.id===id)).slice(0,4)}catch{return []}}
function renderRecent(){let ids=getRecent(),sel=$('car').value;$('recentCars').innerHTML=ids.length?ids.map(id=>{let c=D.cars.find(x=>x.id===id);return c?'<button class="recent-car '+(sel===id?'active':'')+'" data-id="'+e(c.id)+'"><b>'+e(c.plate)+'</b><br><span style="font-size:12px;font-weight:600">'+e(c.name||'')+'</span></button>':''}).join(''):'<div class="small">Zatím žádná.</div>';document.querySelectorAll('.recent-car').forEach(b=>b.onclick=()=>chooseCar(b.dataset.id))}
function rememberCar(id){if(!id)return;try{let r=[id,...getRecent().filter(x=>x!==id)].slice(0,4);localStorage.setItem(recentKey(),JSON.stringify(r))}catch{}renderRecent()}
function renderCarOptions(sel=$('car').value){let q=carSearch.trim().toLocaleUpperCase('cs-CZ'),cars=D.cars.filter(c=>!q||(c.plate+' '+c.name).toLocaleUpperCase('cs-CZ').includes(q)),cur=D.cars.find(c=>c.id===sel);if(cur&&!cars.some(c=>c.id===cur.id))cars=[cur,...cars];$('car').innerHTML='<option value="">'+(cars.length?'Vyber auto…':'Žádné auto nenalezeno')+'</option>'+cars.map(c=>'<option value="'+e(c.id)+'">'+e(c.plate)+' — '+e(c.name)+'</option>').join('');if(cur)$('car').value=sel;renderRecent()}
function chooseCar(id){if(!D.cars.some(c=>c.id===id))return;carSearch='';$('carSearch').value='';renderCarOptions(id);$('car').value=id;rememberCar(id);valid()}
$('carSearch').oninput=()=>{carSearch=$('carSearch').value;renderCarOptions($('car').value)};
$('car').onchange=()=>{rememberCar($('car').value);valid();renderRecent()};
function setSeason(s){season=s;$('summer').classList.toggle('on',s==='summer');$('winter').classList.toggle('on',s==='winter');valid()}$('summer').onclick=()=>setSeason('summer');$('winter').onclick=()=>setSeason('winter');
['1','2','3','4','5','6','7','8','9','C','0','⌫'].forEach(k=>{let b=document.createElement('button');b.textContent=k;b.onclick=()=>{if(k==='C')$('dot').value='';else if(k==='⌫')$('dot').value=$('dot').value.slice(0,-1);else if($('dot').value.length<4)$('dot').value+=k;valid()};$('pad').append(b)});
$('save').onclick=async()=>{if($('save').disabled)return;let id=$('car').value,km=+$('km').value,l=latest(id);if(l&&km<l.mileage&&!confirm('Stav km je nižší než poslední evidovaný. Opravdu uložit?'))return;try{await api('addRecord',{carId:id,season,dot:$('dot').value,mileage:km});$('dot').value='';$('km').value='';season='';$('summer').classList.remove('on');$('winter').classList.remove('on');note($('saveMsg'),'✅ Uloženo a sdíleno online.','msg ok');await refresh();setTimeout(()=>$('saveMsg').innerHTML='',1600)}catch{note($('saveMsg'),'Uložení se nepodařilo.','msg err')}};
function render(){let sel=$('car').value;renderCarOptions(sel);valid();renderFleet();renderHist();if(me.role==='admin')renderAdmin()}
function renderFleetUsers(){let current=$('fleetUser').value,users=new Map();D.records.forEach(r=>users.set(r.userId,r.userName));$('fleetUser').innerHTML='<option value="">Všichni uživatelé</option>'+[...users.entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'cs')).map(([id,name])=>'<option value="'+e(id)+'">'+e(name)+'</option>').join('');if([...users.keys()].includes(current))$('fleetUser').value=current}
function filteredFleetCars(){let q=$('fleetSearch').value.trim().toLocaleUpperCase('cs-CZ'),s=$('fleetSeason').value,u=$('fleetUser').value,from=$('fleetFrom').value?new Date($('fleetFrom').value+'T00:00:00').getTime():-Infinity,to=$('fleetTo').value?new Date($('fleetTo').value+'T23:59:59.999').getTime():Infinity,recordFilterActive=!!(s||u||$('fleetFrom').value||$('fleetTo').value);return D.cars.filter(c=>{let hay=(String(c.plate||'')+' '+String(c.name||'')).toLocaleUpperCase('cs-CZ');if(q&&!hay.includes(q))return false;if(!recordFilterActive)return true;return D.records.some(r=>{let ts=new Date(r.createdAt).getTime();return r.carId===c.id&&(!s||r.season===s)&&(!u||r.userId===u)&&ts>=from&&ts<=to})})}
function renderFleet(){renderFleetUsers();let cars=filteredFleetCars(),done=0,part=0,h='';for(let c of cars){let s=latest(c.id,'summer'),w=latest(c.id,'winter'),l=latest(c.id);if(s&&w)done++;else if(s||w)part++;h+='<div class="item"><b>'+e(c.plate)+'</b> '+e(c.name)+'<div class="small">'+(l?Number(l.mileage).toLocaleString('cs-CZ')+' km':'bez km')+'</div><span class="chip '+(s?'good':'')+'">☀️ '+(s?e(s.dot):'chybí')+'</span><span class="chip '+(w?'good':'')+'">❄️ '+(w?e(w.dot):'chybí')+'</span></div>'}$('fleetList').innerHTML=h||'<div class="small">Filtru neodpovídá žádné auto.</div>';$('stats').textContent='Celkem '+cars.length+' · Hotovo '+done+' · Rozpracováno '+part;$('fleetCount').textContent='Zobrazeno '+cars.length+' z '+D.cars.length+' aut';$('fleetExportCsv').disabled=cars.length===0}
['fleetSearch','fleetFrom','fleetTo'].forEach(id=>$(id).oninput=renderFleet);
['fleetSeason','fleetUser'].forEach(id=>$(id).onchange=renderFleet);
$('clearFleetFilters').onclick=()=>{$('fleetSearch').value='';$('fleetSeason').value='';$('fleetUser').value='';$('fleetFrom').value='';$('fleetTo').value='';renderFleet()};
$('fleetRefresh').onclick=refresh;
function exportFleetCsv(){let cars=filteredFleetCars();if(!cars.length)return alert('Filtru neodpovídá žádné auto.');let rows=[['SPZ','Vozidlo','Letní DOT','Zimní DOT','Kilometry'],...cars.map(c=>{let s=latest(c.id,'summer'),w=latest(c.id,'winter'),l=latest(c.id);return[c.plate,c.name,s?s.dot:'',w?w.dot:'',l?l.mileage:'']})],text='\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n'),blob=new Blob([text],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a'),date=new Date().toISOString().slice(0,10);a.href=url;a.download='DOT-Auta-'+date+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('fleetExportCsv').onclick=exportFleetCsv;
function dt(x){return new Intl.DateTimeFormat('cs-CZ',{dateStyle:'short',timeStyle:'short'}).format(new Date(x))}
function renderHistoryUsers(){let current=$('histUser').value,users=new Map();D.records.forEach(r=>users.set(r.userId,r.userName));$('histUser').innerHTML='<option value="">Všichni uživatelé</option>'+[...users.entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'cs')).map(([id,name])=>'<option value="'+e(id)+'">'+e(name)+'</option>').join('');if([...users.keys()].includes(current))$('histUser').value=current}
function filteredRecords(){let q=$('histSearch').value.trim().toLocaleUpperCase('cs-CZ'),s=$('histSeason').value,u=$('histUser').value,from=$('histFrom').value?new Date($('histFrom').value+'T00:00:00').getTime():-Infinity,to=$('histTo').value?new Date($('histTo').value+'T23:59:59.999').getTime():Infinity;return D.records.filter(r=>{let ts=new Date(r.createdAt).getTime(),hay=(String(r.plate||'')+' '+String(r.vehicle||'')).toLocaleUpperCase('cs-CZ');return(!q||hay.includes(q))&&(!s||r.season===s)&&(!u||r.userId===u)&&ts>=from&&ts<=to})}
function renderHist(){renderHistoryUsers();let recs=filteredRecords(),shown=recs.slice(0,300);$('histCount').textContent='Zobrazeno '+recs.length+' z '+D.records.length+' záznamů'+(recs.length>300?' · na obrazovce prvních 300':'');$('exportCsv').disabled=recs.length===0;$('histList').innerHTML=shown.map(r=>'<div class="item"><b>'+e(r.plate)+'</b> · '+(r.season==='summer'?'☀️ Letní':'❄️ Zimní')+' · DOT <b>'+e(r.dot)+'</b><div class="small">'+Number(r.mileage).toLocaleString('cs-CZ')+' km · '+e(r.userName)+' · '+dt(r.createdAt)+'</div>'+(me.role==='admin'?'<button class="danger del" data-p="'+e(r.path)+'" style="min-height:34px;margin-top:6px">Smazat záznam</button>':'')+'</div>').join('')||'<div class="small">Filtru neodpovídá žádný záznam.</div>';if(me.role==='admin')document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(confirm('Smazat tento záznam?')){await api('adminDeleteRecord',{path:b.dataset.p});refresh()}})}
$('refresh').onclick=refresh;
['histSearch','histFrom','histTo'].forEach(id=>$(id).oninput=renderHist);
['histSeason','histUser'].forEach(id=>$(id).onchange=renderHist);
$('clearFilters').onclick=()=>{$('histSearch').value='';$('histSeason').value='';$('histUser').value='';$('histFrom').value='';$('histTo').value='';renderHist()};
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function exportCsv(){let recs=filteredRecords();if(!recs.length)return alert('Filtru neodpovídá žádný záznam.');let rows=[['SPZ','Vozidlo','Sada','DOT','Kilometry','Uživatel','Datum a čas'],...recs.map(r=>[r.plate,r.vehicle,r.season==='summer'?'Letní':'Zimní',r.dot,r.mileage,r.userName,dt(r.createdAt)])];let text='\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n'),blob=new Blob([text],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a'),date=new Date().toISOString().slice(0,10);a.href=url;a.download='DOT-Evidence-'+date+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('exportCsv').onclick=exportCsv;
$('addCar').onclick=async()=>{let plate=$('newPlate').value.trim(),name=$('newName').value.trim();if(!plate)return;try{await api('adminAddCar',{plate,name});$('newPlate').value=$('newName').value='';refresh()}catch(x){alert(x.code==='DUPLICATE'?'SPZ už existuje.':'Nepodařilo se přidat auto.')}};
function renderAdmin(){$('adminCars').innerHTML=D.cars.map(c=>'<div class="item"><b>'+e(c.plate)+'</b> '+e(c.name)+' <button class="danger arch" data-id="'+e(c.id)+'" style="float:right;min-height:34px">Archivovat</button></div>').join('');document.querySelectorAll('.arch').forEach(b=>b.onclick=async()=>{if(confirm('Archivovat auto? Historie zůstane.')){await api('adminArchiveCar',{carId:b.dataset.id});refresh()}});$('users').innerHTML=(D.users||[]).map(u=>'<div class="user"><div class="row"><input class="un" data-id="'+e(u.id)+'" value="'+e(u.name)+'"><input class="up" data-id="'+e(u.id)+'" inputmode="numeric" maxlength="2" placeholder="nový PIN" style="max-width:110px"><span class="badge">'+(u.role==='admin'?'Admin':'Uživatel')+'</span></div><div class="row" style="margin-top:7px"><button class="primary su" data-id="'+e(u.id)+'" style="flex:1">Uložit</button>'+(u.role!=='admin'?'<button class="tu" data-id="'+e(u.id)+'" data-a="'+u.active+'" style="flex:1">'+(u.active?'Deaktivovat':'Aktivovat')+'</button>':'')+'</div></div>').join('');document.querySelectorAll('.su').forEach(b=>b.onclick=async()=>{let id=b.dataset.id,n=document.querySelector('.un[data-id="'+id+'"]').value,p=document.querySelector('.up[data-id="'+id+'"]').value;if(p&&!/^\d{2}$/.test(p))return alert('PIN musí mít 2 číslice.');try{await api('adminUpdateUser',{userId:id,name:n,pin:p});await refresh();alert('Uloženo.')}catch(x){alert(x.code==='PIN_USED'?'PIN už používá někdo jiný.':'Nepodařilo se uložit.')}});document.querySelectorAll('.tu').forEach(b=>b.onclick=async()=>{await api('adminUpdateUser',{userId:b.dataset.id,active:b.dataset.a!=='true'});refresh()})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{if(b.id==='adminTab'&&me.role!=='admin')return;document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.tab==='history'||b.dataset.tab==='admin')refresh()});setInterval(()=>{if(tok)refresh()},12000);if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js');})();
